AUTH_LOGIN_LIMIT = 5
AUTH_LOGIN_WINDOW_SECONDS = 5 * 60

AUTH_REGISTER_LIMIT = 3
AUTH_REGISTER_WINDOW_SECONDS = 5 * 60

AUTH_FORGOT_PASSWORD_LIMIT = 3
AUTH_FORGOT_PASSWORD_WINDOW_SECONDS = 60 * 60

AUTH_RESEND_VERIFICATION_LIMIT = 3
AUTH_RESEND_VERIFICATION_WINDOW_SECONDS = 60 * 60